[constants]
serialID = '16c0:27db'
location = 'Robot_Lab' 
brokerIP = 'localhost'

[docker]
    url = "http://timeseries-db.docker.local:1883"
    frequency_record_seconds = 1
    ## Token for authentication.
