{
 "title": "Faults",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> keep(columns: [\"location\"])\r\n  |> distinct(column: \"location\")\r\n  |> filter(fn: (r) => r[\"location\"] != \"null\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "Hourly Results",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outcome\")\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n  |> keep(columns:[\"_time\",\"outcome\"])\r\n  |> group(columns: [\"outcome\"])\r\n  |> duplicate(column: \"outcome\", as: \"_value\")\r\n  |> aggregateWindow(every: 1h,period:1h, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outcome\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\r\n  |> duplicate(column: \"_value\", as: \"buckets\")\r\n  |> group(columns: [\"buckets\"], mode: \"by\")\r\n  |> count()\r\n  |> pivot(rowKey:[], columnKey: [\"buckets\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Scrapped by part",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"outcome\"] == \"scrap\")\r\n  |> keep(columns:[\"_time\",\"outcome\",\"part\"])\r\n  |> group(columns: [\"outcome\",\"part\"])\r\n  |> duplicate(column: \"outcome\", as: \"_value\")\r\n  |> drop(columns: [\"outcome\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: true)"
    }
   ]
  },
  {
   "title": "rework by part",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"fault_capture\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reported_defect\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"${location}\")\r\n  |> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"outcome\"] == \"rework\")\r\n  |> keep(columns:[\"_time\",\"outcome\",\"part\"])\r\n  |> group(columns: [\"outcome\",\"part\"])\r\n  |> duplicate(column: \"outcome\", as: \"_value\")\r\n  |> drop(columns: [\"outcome\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: true)"
    }
   ]
  }
 ]
}